### ISSUE TITLE
[Feature] Disk Usage Stats 

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/termiboard#1]
**Please describe the feature you want this project to offer**
It would be nice to have disk stats show up in termiboard.

**Describe the solution you'd like**
Implement the GetDiskUsage() method in the ```memory.go``` file.

**Describe alternatives you've considered (Optional)**
You could use the gopsutil library to achieve this

**Comment by S-Maciejewski** [comment]
I would like to tackle this issue :)

**Comment by DarthBenro008** [comment]
Sure @S-Maciejewski
