### ISSUE TITLE
[Feature] Improve readability of Ram Available and Disk Available output

### ISSUE THREAD

**Issue by S-Maciejewski** [IEEE-VIT/termiboard#14]
**Please describe the feature you want this project to offer**
Available RAM and disk space are now just a plain number - they are difficult to read. They should be showing the amount in GB

**Describe the solution you'd like**
The values should be displayed in GB, limited to 2 decimal places

**Comment by DarthBenro008** [comment]
Yes, you are right, make sure to handle mb also.  Please proceed with the issue @S-Maciejewski

**Comment by S-Maciejewski** [comment]
There will be additional function for formatting the number of bytes into readable string. Do we also want a unit test for such method in the scope of this issue?

**Comment by DarthBenro008** [comment]
@S-Maciejewski a unit test is always preferred , feel free to add the additional function!

**Comment by S-Maciejewski** [comment]
Such function is now implemented in PR #20 

It handles a range from bytes to petabytes and is unit tested
