### ISSUE TITLE
[Feature] Add Makefile 

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [IEEE-VIT/termiboard#18]
**Please describe the feature you want this project to offer**
A makefile abstracting away all the commands associated with fiddling around with this project like building, testing, running, etc.

**Describe the solution you'd like**
Makefile added and corresponding documentation for it

**Comment by DarthBenro008** [comment]
@yashvardhan-kukreja even i had thought of initially making a makefile, but as this project aims to be cross-platform, makefile wouldn't make sense to Windows users. If you figure out an alternative for windows (maybe something like both make and nmake), it would be the best to implement both.

**Comment by aryan9600** [comment]
I don't see the harm in adding a makefile though, it can be a Unix _only_ feature for now.

**Comment by MistaTwista** [comment]
I can make Makefile, what commands do you want to be there?

first what comes in mind:

*help* - show commands available (and it will be default behaviour, with just `make`)
*build* - as it sounds, build and put a binary to some place, before it we can run tests
*testing* - runs unit tests

what else?

[Mage](https://magefile.org) is something more cross-platform, doesn't work with it, but it looks simple for cases above

**Comment by yashvardhan-kukreja** [comment]
yep.. 
make help, build, run, update, or any other you can think of.

**Comment by MistaTwista** [comment]
#41 I've added Makefile and some description for it's usage :)
