### ISSUE TITLE
[Feature] Adding Network Interface Name along with the Local IPv4 Addresses

### ISSUE THREAD

**Issue by sjchoure** [IEEE-VIT/termiboard#19]
**Please describe the feature you want this project to offer**
The current output of the program for the Local IP Address is as:
![GitHubIssue](https://user-images.githubusercontent.com/36518515/94857673-837f0800-044f-11eb-8109-b4f04f7b578d.PNG)

**Describe the solution you'd like**

Along with the IP Address, we could Specify the Network Interface name as
 1. Ethernet:  192.168.30.1/24
 2. Wifi:  192.168.1.20/24

**Additional context**
This will make Identifying the IP of each interface simple

**Comment by sjchoure** [comment]
If assigned to me, I am ready to do the necessary changes.

**Comment by DarthBenro008** [comment]
This is much required, thank you for opening this issue! @saviourcode

**Comment by sjchoure** [comment]
For some reasons, I couldn't add "Hacktober" Label to this issue. @DarthBenro008 can you please add the "Hacktober" label. 😃
