### ISSUE TITLE
[Feature] Updating README.md with the new section for flag options

### ISSUE THREAD

**Issue by sjchoure** [IEEE-VIT/termiboard#24]
**Please describe the feature you want this project to offer**
After adding the flag parsing functionality to the program, the README.md file does not reflect the usage of it, as was done in PR #17  

**Describe the solution you'd like**
We can have a proper section for the usage of this program, such as an example block in the README.md file

**Comment by sjchoure** [comment]
If assigned to me, I am ready to do the necessary changes.

**Comment by DarthBenro008** [comment]
I am closing this issue as of now, will reopen once most of the features have been implemented and tested!

**Comment by aryan9600** [comment]
We had an internal discussion, we decided to go ahead with it. Please rebase the current PR wrt master :)

**Comment by sjchoure** [comment]
@aryan9600 Yes, I have reopened the PR #25
