### ISSUE TITLE
[Feature] Display local IP address

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/termiboard#3]
**Please describe the feature you want this project to offer**
It would be nice if termiboard can show the local IP address that the computer is currently connected to.

**Describe the solution you'd like**
You can implement the  GetLocalIPAddress() function in the ```network.go``` file. Make sure to handle if the computer isn't connected to a network!

**Comment by 0vj** [comment]
Can you assign it to me?I would like to work on it

**Comment by DarthBenro008** [comment]
Sure @mr-tafreshi , best of luck ! :)
