### ISSUE TITLE
[BUG] Process with PID: 0 access denied as it is system idle process in Windows

### ISSUE THREAD

**Issue by sjchoure** [IEEE-VIT/termiboard#30]
**Describe the bug**
Since the PID of system processes in Windows and Unix differ, for example,
`PID 0` and `PID 1` in *nix are given to the Scheduler and the Init Process respectively. _Note: Unix PID starts from 1_
`PID 0` and `PID 4` in Windows are given to the System Idle Process and the Init Process respectively. _Note: Windows PID starts from 4_

So, the System Idle Process in Windows is generally not accessible by the userland programs not even by the administrative privileges.

**To Reproduce**
1. Run the current program in Windows and the Output is as follows:
![Githubwin](https://user-images.githubusercontent.com/36518515/94919215-c386cf00-04d1-11eb-85a6-38c0b8830825.PNG)

**Expected behavior**
1. Running the same program in *nix based OS gave the desired Output.
![GithubNewIssue](https://user-images.githubusercontent.com/36518515/94919282-e2856100-04d1-11eb-8c0e-2b345eab6e64.PNG)

**Additional context (Optional)**
The solution is to slice off the PID = 0 if present in the `Processes` Slice inside the `memory.go` file. This result in the desired output without the error as follows:

![Github Issue](https://user-images.githubusercontent.com/36518515/94920357-c71b5580-04d3-11eb-959c-c368d0301155.PNG)
_Note: We still require to "Run as an Admin" to get the desired result_

**Comment by DarthBenro008** [comment]
@saviourcode i would highly suggest you add a os check (using GOOS ) and then slice of PID 0 if its windows

**Comment by sjchoure** [comment]
> @saviourcode i would highly suggest you add a os check (using GOOS ) and then slice of PID 0 if its windows

Yeah, that way is more acceptable and maintainable in long run, rather than slicing random PID: 0, 😃 Okay I will make the changes.
