### ISSUE TITLE
[Feature] Moving all Flag Options to it's own new file

### ISSUE THREAD

**Issue by sjchoure** [IEEE-VIT/termiboard#32]
**Please describe the feature you want this project to offer**
All the flag options and variables are in `main.go` among other functions. Thus reducing the readability of the code inside the `main.go`.

In the light of separating the **specification** and **implementation**, we would like to create a new separate file for all the flag options and it's variable, making the `main` function more readable.

**Describe the solution you'd like**
1. `vim/nano flag.go`
2. Move all flag helper variables and functions to this new file
3. `:wq` / (`^x` and then `y`)
4. Call the new `initflag` function inside `main.go`

**Additional context**
Readability and Maintainability of code increases

**Comment by DarthBenro008** [comment]
This is would be automatically handled as there will be a refactor of termiboard where we will shift to organisation of mods instead of decoupled files! Thank you for raising this issue :)
