### ISSUE TITLE
[Feature] Flags to hide header and version

### ISSUE THREAD

**Issue by Vulwsztyn** [IEEE-VIT/termiboard#37]
**Please describe the feature you want this project to offer**
PR's funtionality should base on 3 flags:
 - 1 to hide header
 - 1 to hide version
 - 1 to hide them both

**Describe the solution you'd like**
They should be implemented in the same way as other flags and conditions to show header and version should be updated from `true`.

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Additional context**

disclaimer: I don't want to be assigned for now

**Comment by DarthBenro008** [comment]
I do not feel hiding the banner or version is necessary.

**Comment by Vulwsztyn** [comment]
That's why I wanted to implement it as flags, so that users can decide whether they want it displayed or not. Moreover it's `good first issue`.
