### ISSUE TITLE
[Documentation] Update README to have a "Usage" section

### ISSUE THREAD

**Issue by aryan9600** [IEEE-VIT/termiboard#39]
It'd be helpful for new contributors to see what all features the cli provides and how to use it! We can have a table with two columns: one for the flag, and a short description corresponding to that flag.

**Comment by DarthBenro008** [comment]
@saviourcode would you resend the PR with updated Readme?

**Comment by sjchoure** [comment]
@DarthBenro008 Sure, Reopening it

**Comment by aryan9600** [comment]
Closing this as a duplicate of #24
