### ISSUE TITLE
[Feature] To check if common ports are free.

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/termiboard#4]
**Please describe the feature you want this project to offer**
To check if a set of ports are available and free at time of termiboard execution.

Eg: to check common ports such as 80,443,3000,5000,5432,27017,8080,8000 are available

**Describe the solution you'd like**
Implement the PortChecker() function in the ```network.go``` file.

**Comment by arrwhidev** [comment]
I can take this one, if you'd like to assign to me?

**Comment by DarthBenro008** [comment]
Sure @arrwhidev ! Best of luck!
