### ISSUE TITLE
[Feature] To obtain the public IP address of the computer.

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/termiboard#5]
**Please describe the feature you want this project to offer**
To display the public IP address of the computer at time of termiboard execution.

**Describe the solution you'd like**
Implement the  GetPublicIPAddress() function of the ```network.go``` file. 

**Describe alternatives you've considered (Optional)**
You can make a small network call/ping that returns your public IP address as a response.

**Comment by sjchoure** [comment]
Hey @DarthBenro008 hope you are doing well! I have been working on Golang over past few months and want to improve my skills at it. Can I take up this issue?

**Comment by DarthBenro008** [comment]
Sure @saviourcode ! Best of luck ! :)
