### ISSUE TITLE
[Feature] Show CPU Usage

### ISSUE THREAD

**Issue by DarthBenro008** [IEEE-VIT/termiboard#6]
**Please describe the feature you want this project to offer**
Show CPU Usage at termiboard execution in percentage.

**Describe the solution you'd like**
Implementation of GetCpuUsage() in ``cpu.go``` file.

**Describe alternatives you've considered (Optional)**
You can leverage the gopsutil library.

**Comment by S-Maciejewski** [comment]
You can assign me to it, I want to give it a try :)

**Comment by DarthBenro008** [comment]
Sure @S-Maciejewski , best of luck ! :)

**Comment by S-Maciejewski** [comment]
Should this be an overall value, or separate for each CPU? We could display it as a small ASCII table displayed by ResultPrinter

**Comment by DarthBenro008** [comment]
@S-Maciejewski the purpose of termiboard is to give instant stats of most hardware with one command, so it should be an overall value of cpu usage, however feel free to create a another function and make it print an ASCII table(core-wise usage), but for the scope of this issue , we require an overall value.
